use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'LiveChat-IOS_Example' do
  pod 'LiveChatIOS-SDK', :git => "https://github.com/ngnahtn/LiveChatIOS-SDK", :commit => 'd69f134'
  pod 'Alamofire', '5.6'
  pod 'lottie-ios', '3.5.0'
  pod 'ScClient'

end
