use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'LiveChat-IOS_Example' do
  pod 'LiveChatIOS-SDK', :path => '../'
  pod 'Alamofire', '5.6'
  pod 'lottie-ios', '3.5.0'
  pod 'ScClient'

end
